image: k33g/wasm-builders-sat:0.0.0

tasks:
  - name: initialize
    init: |
      echo "🚀 initialize"

ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public


vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - rust-lang.rust
    - bungcip.better-toml
