image:
  file: .gitpod.dockerfile
# image: k33g/wasm-builders-sat:0.0.0


tasks:
  - name: initialize
    init: |
      echo "🚀 initialize"
      #sudo chown -R $USER .

ports:
  - port: 8080
    visibility: public

vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - rust-lang.rust
    - bungcip.better-toml
